### ISSUE TITLE
Create Dockerfile and upload docker image to dockerhub

### ISSUE THREAD

**Issue by chb0github** [mybatis/migrations#105]
The installation process is well described but still a bit involved.

A great enhancement would be to create and push a docker image on build. This would  entirely eliminate the installation process for those choosing the image. You could do:

`docker run -it -v $PWD:/root -w /root mybatis/migrations migrate`

This also gives you a path forward for using Java 8

**Comment by h3adache** [comment]
lol I was thinking about this a lot recently

**Comment by chb0github** [comment]
You would need to update your build process to create the image and upload it to dockerhub

**Comment by schumacher-m** [comment]
We do something like that to do a "docker-compose run bin/mybatis ..." on different machines. Maybe this helps to get something similar in the meantime. In theory this could also be used for a dockerhub image. It just needs a wrapper entrypoint.sh to the mybatis bin so you can enter the commands directly. 
Then we could use this: https://github.com/spotify/dockerfile-maven

Is this considered worthy to spend time on? 

./docker/mybatis/Dockerfile
```FROM openjdk:8
RUN ["mkdir", "-p", "/opt/mybatis/migrations"]
WORKDIR /opt/mybatis
ADD mybatis-migrations-3.3.2-SNAPSHOT-bundle.zip /opt/mybatis
RUN ["unzip", "*.zip"]
RUN mv mybatis-migrations-3.3.2-SNAPSHOT/* .
RUN ["rmdir", "mybatis-migrations-3.3.2-SNAPSHOT"]
VOLUME ["/opt/mybatis/migrations"]``` 

docker-compose.yml
```
version: "2"
services:
  mybatis:
    container_name: mybatis
    build:
      context: ./docker/mybatis
      dockerfile: Dockerfile
    environment:
      - MIGRATIONS_HOME=/opt/mybatis
      - MIGRATIONS=/opt/mybatis/bin
    volumes:
      - ./migrations:/opt/mybatis/migrations
    links:
      - postgres:db

  postgres:
    image: postgres:9.6
    ports:
      - 5432
```

**Comment by chb0github** [comment]
the `Dockerfile` makes sense to checkin but not the compose. If you create a branch I will collab with you on it.

**Comment by svscorp** [comment]
I'd say compose us also good to have (maybe in examples or so?)

**Comment by h3adache** [comment]
closed by https://hub.docker.com/r/mybatis/migrations
