### ISSUE TITLE
before_new and after_new hooks

### ISSUE THREAD

**Issue by chb0github** [mybatis/migrations#106]
I would like to implement before/after `new` hooks as they exist for the other hooks. Any objections?

**Comment by chb0github** [comment]
I am also willing to fold-in a dockerfile as per #105 to see this change accepted.

**Comment by harawata** [comment]
Hi @chb0github ,

Could you elaborate on the use case?
`new` command is rather unique and we may need to know what you are trying to achieve with the hooks to make it useful.

**Comment by chb0github** [comment]
When a new migration is created we need to create a few other corresponding
resources based on the file to be created. In addition, it allows
flexibility for doing  validation on the naming of the file as they are
based on jira tickets

**Comment by chb0github** [comment]
To be clear, it's a feature I am willing to implement. I just need to know
it will be folded in if implemented

**Comment by harawata** [comment]
Thank you for the explanation!
Description validation looks useful.

There is one thing I would like to discuss first.
As `new` is one of the commands that are independent of environment, the environment properties file does not seem to be the right place to configure new-hooks.
What do you guys think about adding a per-project configuration file and store environment-independent settings?

As a background, `script_char_set` also is independent of environment and I have been thinking about (gradually) migrating it to the per-project config file.

Cc-ing @h3adache .

**Comment by chb0github** [comment]
I don't have much knowledge on the subject, but let me ask:

What's the difference between `mybatis.properties` and an environment property set? Outside of the local directory, what more is needed?

put it all in `mybastis.properties` and have the default environment something you can configure

As for the hooks: I would say that git has the right idea: create a `.hooks` directory and use convention. I mean, the migration scripts are run based on convention so why should the hooks be by configuration? 

And, putting them in a `.hooks` directory keeps the project uncluttered as it's a hidden directory. 

So, like `01_before_up_dosomething.groovy`

**Comment by chb0github** [comment]
I have a working implementation of `new` hooks. It follows current coding conventions and hook mechanisms. Our discussion about other changes went nowhere. So, I would like to get this accepted and have discussions about refactoring occur after

**Comment by harawata** [comment]
Thank you, @chb0github .
before_new and after_new hooks are now available in the latest 3.3.5-SNAPSHOT.
