### ISSUE TITLE
Migration Down Fails in 3.3.2 if you don't have have a return char on sql statement.

### ISSUE THREAD

**Issue by h3adache** [mybatis/migrations#117]
```
CREATE TABLE test.[Migration Failure] (
  ID BIGINT IDENTITY PRIMARY KEY,
  [Test] VARCHAR(255) NOT NULL
);
-- //@UNDO
DROP TABLE test.[Migration Failure];
```
up + down successfully completes but down is an empty statement.

```
CREATE TABLE test.[Migration Failure] (
  ID BIGINT IDENTITY PRIMARY KEY,
  [Test] VARCHAR(255) NOT NULL
);
-- //@UNDO
DROP TABLE test.[Migration Failure];

```
up + down successfully correctly. The only difference is adding a return after the DROP statement.
Probably relates to #101 but need to investigate more.

**Comment by h3adache** [comment]
Nice, quick find! Yea, we should do a quick release for this one. Thanks!

**Comment by harawata** [comment]
3.3.3 is [out](http://repo1.maven.org/maven2/org/mybatis/mybatis-migrations/3.3.3/). Thank you, @h3adache !

**Comment by h3adache** [comment]
Hi @harawata this bug is still there but on the down stage. It doesn't replace ${changelog} if it's not followed by a return character :P
I can look into it if you don't have time.

**Comment by harawata** [comment]
@h3adache , XD
Sorry, I should've waited for your verification. It's fixed in the snapshot.

**Comment by h3adache** [comment]
@harawata thanks! I tried the 3.3.4-SNAPSHOT and it looks great!

**Comment by harawata** [comment]
Thank you, @h3adache !
Let's wait for a while before releasing 3.3.4 ;D
