### ISSUE TITLE
Feature: Out-of-Order migrations

### ISSUE THREAD

**Issue by svscorp** [mybatis/migrations#119]
Hi team,

Currently if I run migration against files with timestamps that are older than latest in the CHANGELOG database - these files are being skipped. Is it possible to have a flag to force MyBatis to apply older migrations if they were not found/applied in CHANGELOG?

**Comment by harawata** [comment]
Hi @svscorp ,
Have you checked `pending` command?
http://www.mybatis.org/migrations/pending.html
