### ISSUE TITLE
'script' command can generate incomplete script

### ISSUE THREAD

**Issue by poojagit912** [mybatis/migrations#121]
Hi Team,

We are executing migrate script on the .sql file which has undo section of more than 100 lines, but the output we get is only 10 lines.

Is there any way to get the whole undo section.

**Comment by harawata** [comment]
Hi @poojagit912 ,

I'm sorry for the late response, but the problem should be resolved in the latest 3.3.5-SNAPSHOT.
It would be great if you could verify the fix when you have some spare time.

Thank you for the report!
Iwao
