### ISSUE TITLE
Skipped installation gives result as success. Can it be changed to 'Failure' or at-least a Warning message?

### ISSUE THREAD

**Issue by Anusha2605** [mybatis/migrations#123]
The issue is that, currently the latest entry in changelog table is the one with current timestamp. if we try to install a file with timestamp lesser than the latest one in changelog, it skips the installation and returns the result as success. It would be better if that result is a failure message or at-least a warning message.

**Comment by harawata** [comment]
Thank you for the suggestion, @Anusha2605 .
Migrations now prints WARNING message. Please see #125 for the details.
It would be great if you could verify the feature with 3.3.5-SNAPSHOT.
