### ISSUE TITLE
Possible ArrayIndexOutOfBoundsException when reading DO part of a script

### ISSUE THREAD

**Issue by lgdop** [mybatis/migrations#127]

**Comment by lgdop** [comment]
I suspect below is the cause, that is because of providing a comment of 345 characters length in migration script.
For example:
/*aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa*/

**Comment by harawata** [comment]
Hi @lgdop ,

Adding the comment to a migration script didn't reproduce the exception with Migrations 3.3.4 and MySQL 5.7.22 (Connector/J 8.0.11).

Please add ```--trace``` command line option and it will print the stack trace.

```sh
$ migrate --trace up
```

We may also need the following information.

- Migrations version. Run ```migrate info```.
- DB vendor and version (e.g. MySQL 5.7.22, Oracle 10g, etc.)
- JDBC driver version.

**Comment by luryson** [comment]
"java.lang.ArrayIndexOutOfBoundsException" was thrown when length of one single line of sql exceeded 1024 chars.

**Comment by harawata** [comment]
@luryson ,

I still could not reproduce it.
Could you provide the information I requested in my previous comment?

**Comment by luryson** [comment]
@harawata 
<pre>
ERROR: java.lang.ArrayIndexOutOfBoundsException
org.apache.ibatis.migration.MigrationException: java.lang.ArrayIndexOutOfBoundsException
	at org.apache.ibatis.migration.CommandLine.runCommand(CommandLine.java:81)
	at org.apache.ibatis.migration.CommandLine.execute(CommandLine.java:45)
	at org.apache.ibatis.migration.Migrator.main(Migrator.java:20)
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at java.lang.AbstractStringBuilder.getChars(AbstractStringBuilder.java:388)
	at java.lang.StringBuilder.getChars(StringBuilder.java:76)
	at org.apache.ibatis.migration.MigrationReader.readFromBuffer(MigrationReader.java:175)
	at org.apache.ibatis.migration.MigrationReader.read(MigrationReader.java:127)
	at java.io.Reader.read(Reader.java:140)
	at org.apache.ibatis.migration.commands.ScriptCommand.execute(ScriptCommand.java:86)
	at org.apache.ibatis.migration.CommandLine.runCommand(CommandLine.java:75)
	... 2 more
</pre>

**Comment by Anusha2605** [comment]
1. Migrations version. Run migrate info.
 - Run Mybatis
------------------------------------------------------------------------
-- MyBatis Migrations - info
------------------------------------------------------------------------
null 3.3.5-SNAPSHOT (null)
Java version: 1.6.0_41, vendor: Sun Microsystems Inc.
Java home: /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "Linux", version: "4.13.3-1.el7.elrepo.x86_64", arch: "amd64", family: "unix"
DB vendor and version (e.g. MySQL 5.7.22, Oracle 10g, etc.)
JDBC driver version.

2. DB vendor and version (e.g. MySQL 5.7.22, Oracle 10g, etc.)
Oracle - version varies from 8 to 12

3. JDBC driver version. 
ojdbc14

**Comment by luryson** [comment]
------------------------------------------------------------------------
-- MyBatis Migrations - info
------------------------------------------------------------------------
null null (null)
Java version: 1.8.0_152, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "Mac OS X", version: "10.13.6", arch: "x86_64", family: "mac"
------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Mon Sep 03 21:55:28 CST 2018
-- Final Memory: 2M/123M
------------------------------------------------------------------------

**Comment by harawata** [comment]
Thanks for your help, @luryson !
I've found my mistake. :D

**Comment by luryson** [comment]
@harawata cool

**Comment by harawata** [comment]
Reproducing the problem is always the hardest part. :)
Anyway, the fix is available in the latest 3.3.5-SNAPSHOT.
Please let us know if you find any problem.

And again, thank you both for taking the time to report!
