### ISSUE TITLE
non-timestamp sequence

### ISSUE THREAD

**Issue by roboll** [mybatis/migrations#14]
we use migrations, but with manually sequenced files instead of the timestamps generated by `migrate new`. i have some code to introduce a property to switch between sequence types for the `new` command - would you be willing to accept this upstream? if so, i'll submit a pr to include it.

**Comment by nmaves** [comment]
Robert can your provide an example of what a manually sequenced file name might be?  You are welcome to submit a pull request, I just can't give you an answer without seeing some more code.

**Comment by robertcboll** [comment]
```
0001_description_one.sql
0002_description_two.sql
```

**Comment by WalterPhillips** [comment]
Check out this pull request: https://github.com/mybatis/migrations/pull/16

**Comment by harawata** [comment]
As it is not a per-environment setting, I have fixed this by adding a new option ```idpattern```.

You can specify the format 1) in command line

```bash
$ migrate --idpattern=000 init
$ migrate --idpattern=000 new "description one"
```

or 2) in the migration.properties file

```
idpattern=000
```

Some examples:
- idpattern=0 -> 1_changelog.sql
- idpattern=000 -> 001_changelog.sql

Note that it increments the number of the newest existing script.
