### ISSUE TITLE
Support for Postgresql/CockroachDB?

### ISSUE THREAD

**Issue by Bessonov** [mybatis/migrations#141]
I'm trying to migrate from MariaDB/AuroraDB to CockroachDB. I'm not sure about it, but I wonder how can it work with Postgresql or CockroachDB for statements like [this](https://github.com/mybatis/migrations/blob/master/src/main/java/org/apache/ibatis/migration/operations/DatabaseOperation.java#L53):

```
test=# select ID, APPLIED_AT, DESCRIPTION from changelog_auth;
ERROR:  column "id" does not exist
LINE 1: select ID, APPLIED_AT, DESCRIPTION from changelog_auth;
               ^
```

It works on both databases, if columns passed as strings:

```
test=# select "ID", "APPLIED_AT", "DESCRIPTION" from changelog_auth;
       ID       |     APPLIED_AT      |           DESCRIPTION            
----------------+---------------------+----------------------------------
 20170614124900 | 2017-11-09 08:40:06 | create changelog
 20170614131400 | 2017-11-09 08:40:07 | initialize tables
[...]
```

Do I miss something?

Thank you!

**Comment by harawata** [comment]
Hi @Bessonov ,

Did you modify the first migration script (i.e. xxx_create_changelog.sql) generated by the `init` command?
According to the [doc](https://www.cockroachlabs.com/docs/stable/keywords-and-identifiers.html#rules-for-identifiers), it happens only if you used double-quotes when creating the table and the built-in template does not use double quotes.
https://github.com/mybatis/migrations/blob/8941e0aa79c415cf3db360ebad50ecd50c099909/src/main/java/org/apache/ibatis/migration/template_changelog.sql#L12-L16

**Comment by Bessonov** [comment]
@harawata thank you very much for your quick and insightful response!

> You can also use double-quotes **to preserve case-sensitivity** in database, table, view, and column names.

I didn't modified the changelog script, but well, looked at intermediate PostgreSQL dump I see:

```
CREATE TABLE public.changelog_auth (
    "ID" numeric(20,0) NOT NULL,
    "APPLIED_AT" character varying(25) NOT NULL,
    "DESCRIPTION" character varying(255) NOT NULL
);
```
I've not tested yet, but I think it is.
