### ISSUE TITLE
Release 3.3.6 material structure is different from usual

### ISSUE THREAD

**Issue by seriwb** [mybatis/migrations#148]
Release 3.3.6 includes the feature I wanted. thank you.
But, a few things are different from usual.

- missing bin directory
- mybatis-migrations-3.3.6.jar is not in lib directory

I'm glad that it's the usual structure.

**Comment by harawata** [comment]
Thank you for letting us know, @seriwb !
I have replaced the zip archive on the [release page](https://github.com/mybatis/migrations/releases/tag/mybatis-migrations-3.3.6).

**Comment by seriwb** [comment]
@harawata 
I confirmed it is back! thanks
