### ISSUE TITLE
Incompatible MigrationTemplate change

### ISSUE THREAD

**Issue by thorstenwitt** [mybatis/migrations#157]
We used the version 3.1.0 of mybatis migration where template is:

```
--// ${description}
-- Migration SQL that makes the change goes here.



--//@UNDO
-- SQL to undo the change goes here.
```

Now we want to update mybatis migration to 3.3.6 and found out that the template changed to:

```
-- // ${description}
-- Migration SQL that makes the change goes here.



-- //@UNDO
-- SQL to undo the change goes here.
```

Now I got always a syntax error when I try to execute:

`migrate up`

Could you please make the app accepting the old template style.

**Comment by harawata** [comment]
Hello @thorstenwitt ,

It may be the result of #101 (the change explained in 2).
Although it seems like a trivial change, it actually makes a big difference to the parser logic and its performance, so I would rather not bring back the support for the old template style.
I understand the frustration, but isn't it possible for you to replace `--//` with `-- //` once and for all?

**Comment by thorstenwitt** [comment]
Hello @harawata 

Of course it is possible. 
I just had the hope that there is a workaround our something to customize the template.

**Comment by harawata** [comment]
Hi @thorstenwitt ,

I might have misunderstood.

I thought it was your old migration script generated by Migrations 3.1.0 (which contains `--//`) causing the syntax error when you executed `migrate up` using Migrations 3.3.6 (this could happen if you use MariaDB or Db2).

But was it actually the script generated by Migrations 3.3.6 (which contains `-- //`)  causing the error?
Then which DB/driver do you use?

---

> I just had the hope that there is a workaround our something to customize the template.

You can tell Migrations to use a custom template by setting `new_command.template` configuration option. Please see the [doc](http://mybatis.org/migrations/new.html).

```ini
new_command.template=templates/new_template_migration.sql
```

**Comment by harawata** [comment]
No response.
Let me know if my questions weren't clear enough.
