### ISSUE TITLE
migrate version fails on empty database

### ISSUE THREAD

**Issue by Anonymous-Coward** [mybatis/migrations#160]
Steps to reproduce:
- create an empty migrations directory
- develop some migrations on a local database
- create/configure a second environment, targeting another database, which is empty
- run migrate version <some version> for the second environment, using a valid migration version

Expected results:
- the second database gets updated to the specified version, even if it is not the last

Actual results:
- the migrations execution fails with an error message stating that the changelog table is missing

Background: in continuous integration setups, you don't always want to migrate to the latest version. The migrations in the source code repository may be well ahead of what needs to be deployed into a test environment, therefore you only update the database for that test environment to the database version corresponding to the app version that gets deployed there. That test environment may get reset to the initial state upon each deployment.

Workaround that works: first run migrate up, and only then run migrate version <version>. But that's not nice or convenient, especially when having a lot of migrations between head and what needs to be deployed.

**Comment by harawata** [comment]
Thank you for the report, @Anonymous-Coward !

I have committed a fix.
It would be great if you could verify the fix using the latest [3.3.7-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/mybatis-migrations/3.3.7-SNAPSHOT/).

**Comment by Anonymous-Coward** [comment]
I would love to test this, but I'm using mybatis migrations through the maven plugin, and unfortunately don't have the time to set up a test env right now. But I'm happy to hear it's fixed - it will eventually get pushed to the maven plugin too, I suppose.

**Comment by harawata** [comment]
As it's been a while since the last release, we released 3.3.7.
https://repo1.maven.org/maven2/org/mybatis/mybatis-migrations/3.3.7/

The maven plugin hasn't been updated for a while as there has been no real change.
You can use a newer version (or a snapshot version) of Migrations by specifying the plugin dependency explicitly in your pom.xml.

```xml
<plugin>
  <groupId>org.mybatis.maven</groupId>
  <artifactId>migrations-maven-plugin</artifactId>
  <version>1.1.3</version>
...
  <dependencies>
    <dependency>
      <groupId>org.mybatis</groupId>
      <artifactId>mybatis-migrations</artifactId>
      <version>3.3.7</version>
    </dependency>
  </dependencies>
</plugin>
```

**Comment by Anonymous-Coward** [comment]
Just checked, 3.3.7 is not yet available on mvnrepository.com. Do you have a repo URL for me too, or will it get published soon?

**Comment by harawata** [comment]
It takes a while for a new version to show up on mvnrepository.com as they have index interval (I guess). It's now visible.
https://mvnrepository.com/artifact/org.mybatis/mybatis-migrations/3.3.7
