### ISSUE TITLE
JVM parameter PermSize=128m was not supported by JDK1.8

### ISSUE THREAD

**Issue by zhaokewugou** [mybatis/migrations#167]
issue :
 When I use mybatis migrations tool in my project. It shows an error that OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0.  I searched some documentations, and found that JDK1.8 will not support option `PermSize=128m`. So should we modify the pom.xml. 
https://github.com/mybatis/migrations/blob/mybatis-migrations-3.3.7/pom.xml#L154

**Comment by harawata** [comment]
You are right.
Thank you for the report, @zhaokewugou !
