### ISSUE TITLE
Timestamp on init

### ISSUE THREAD

**Issue by rpm75** [mybatis/migrations#17]
Hi,

migrate init creates folders and files, including some .sql scripts with timestamps.
Problem is that those sql scripts use default timestamp (time_zone = GMT+0) and I would like to initialize those scripts with my correct timezone (GMT+2). 

It should be possible to either
1) pass a "time_zone" parameter to the init command, so that files are created with the proper timestamp
OR
2) remove the check for empty directories to the "init" and allow at least a .properties to be there so I can enter the right "time_zone"

Regards,
Roberto

**Comment by h3adache** [comment]
Support for this was added by @harawata for issue #2 if this isn't what you were asking we can reopen this.
