### ISSUE TITLE
[Feature request] Preserve blank lines in statements during script migrations

### ISSUE THREAD

**Issue by sjanssens1977** [mybatis/migrations#171]
The following migration script is used to insert some markdown text into a Postgresql text column.

```
CREATE TABLE meeting(
    agenda TEXT
)
;
INSERT INTO meeting(agenda) VALUES(
    'Sample markdown

1. First item on the agenda
2. Second item that needs some attention

    This is part of the second item (same indention level) but is separated by a blank line.
3. Third item'
)
;

-- //@UNDO
DROP TABLE meeting
;
```

Retrieving the value from the agenda column gives the following text

```
Sample markdown
1. First item on the agenda
2. Second item that needs some attention
    This is part of the second item (same indention level) but is separated by a blank line.
3. Third item
```

This is not the original text from the migration script.
**The blank lines (in this case containing only carriage return and new line characters) are missing.**
The result is a difference in representation between the original markdown and the markdown retrieved from the database.

This behavior seems to be caused by the org.apache.ibatis.jdbc.ScriptRunner implementation.

```
...
  private void handleLine(StringBuilder command, String line) throws SQLException {
    String trimmedLine = line.trim();
    if (lineIsComment(trimmedLine)) {
      Matcher matcher = DELIMITER_PATTERN.matcher(trimmedLine);
      if (matcher.find()) {
        delimiter = matcher.group(5);
      }
      println(trimmedLine);
    } else if (commandReadyToExecute(trimmedLine)) {
      command.append(line.substring(0, line.lastIndexOf(delimiter)));
      command.append(LINE_SEPARATOR);
      println(command);
      executeStatement(command.toString());
      command.setLength(0);
    } else if (trimmedLine.length() > 0) {
      command.append(line);
      command.append(LINE_SEPARATOR);
// The next 2 lines are added by me to preserve the blank lines in the sql statement. Unfortunately this fix cause some unit test failures.  
    } else if (trimmedLine.length() == 0) {
      command.append(LINE_SEPARATOR);
        }
  }
...
```

The above code snippet fixes the issue but causes some unit tests to fail which I do not fully understand.

Is is possible to preserve blank lines during script migrations without breaking some other functionality?

Behavior tested using MyBatis Migrations version 3.3.5

**Comment by harawata** [comment]
Hello @sjanssens1977 ,

I'm sorry about the belated reply.

Relying on the line break of the file may not be a good idea (it could be modified by SCM).
The recommended way is to use string functions to build the text. e.g.

```sql
INSERT INTO meeting(agenda) VALUES(
  'Sample markdown' || CHR(13) || CHR(13) ||
  '1. First item on the agenda' || CHR(13) ||
  '2. Second item that needs some attention' || CHR(13) ||
  '    This is part of the second item (same indention level) but is separated by a blank line.' || CHR(13) ||
  '3. Third item'
)
;
```

**Comment by sjanssens1977** [comment]
Hello @harawata ,

No worries about the delay, it's summer time in Europe so a lot of people are on holiday.

I agree that relying on a line break may cause issues with SCM.
The workaround makes the conversion from Markdown to SQL statement a little bit more cumbersome but will work.

Thanks for the advice.
