### ISSUE TITLE
Can't insert record of migrate up in changelog.

### ISSUE THREAD

**Issue by printjs** [mybatis/migrations#172]
```sql
-- // Create Changelog

-- Default DDL for changelog table that will keep
-- a record of the migrations that have been run.

-- You can modify this to suit your database before
-- running your first migration.

-- Be sure that ID and DESCRIPTION fields exist in
-- BigInteger and String compatible fields respectively.

CREATE TABLE ${schema}.${changelog} (
    ID NUMERIC(20,0) NOT NULL,
    APPLIED_AT VARCHAR(25) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CONSTRAINT PK_${changelog} PRIMARY KEY (ID)
);


-- //@UNDO

DROP TABLE ${schema}.${changelog};
```

I use postgresql.  I got an error when I exec "migrate up". The ERROR message like fellow:
```shell
ERROR: Error executing command.  Cause: org.postgresql.util.PSQLException: ERROR: relation "changelog" does not exist
  Position: 13
```
But The changelog table has been created.

I think the error reason is migrations insert the record of "create table test.changelog" in public schema but I created the table in test schema. So how to resolve it. May be the reason is not correct. Someone help me ? Thank you.

**Comment by h3adache** [comment]
Hi @printjs!

The easiest way is to configure your database in your connection string use Postgres syntax (database and schema are the same in Postgres)

`jdbc:postgresql://host/database`

Otherwise, Mybatis won't know what schema you are writing to.

Another way to do it is to change the `changelog` property to contain your schema name as well. But if you do it that way you have to remember to name the schema in your scripts.

**Comment by printjs** [comment]
@h3adache Hi, About function one. `jdbc:postgresql://host/database` only provides type of database, host address and database. The connection can't provides schema. So I can't insert data when the table not in public schema. I must make it clear that the schema name is in the sql statement.
My issue is "migrate up" can't insert record of "create table test.changelog". The insert sql is automatic generation. I can't modify lt. About function two. Can you give me a example or some links. I don't understand you because I'm new Java.

**Comment by h3adache** [comment]
Can you provide an example project on your github?

**Comment by printjs** [comment]
@h3adache Yes, of course. The address is `https://github.com/printjs/migration_stock` thanks.

**Comment by h3adache** [comment]
Remove the `schema` config from your `local.properties` and your `create_changelog.sql` script and use
`currentSchema=test` in your connection url as documented https://jdbc.postgresql.org/documentation/head/connect.html

**Comment by printjs** [comment]
@h3adache Thank you.
