### ISSUE TITLE
Driver Class Load Failure on 3.3.8

### ISSUE THREAD

**Issue by kenny-qiao** [mybatis/migrations#176]
## Background
![image](https://user-images.githubusercontent.com/23731080/100220644-9e9f5d00-2f52-11eb-908b-0280a928333f.png)

Upgrade migration version from 3.3.7 to 3.3.8, then error happened like:

```
------------------------------------------------------------------------
-- MyBatis Migrations - up
------------------------------------------------------------------------
------------------------------------------------------------------------
-- MyBatis Migrations FAILURE
-- Total time: 0s
-- Finished at: Wed Nov 25 19:08:37 CST 2020
-- Final Memory: 7M/479M
------------------------------------------------------------------------

ERROR: Error creating ScriptRunner.  Cause: java.lang.ClassNotFoundException: org.mariadb.jdbc.Driver
```

**JDBC connection properties**:
![image](https://user-images.githubusercontent.com/23731080/100220943-fb9b1300-2f52-11eb-8e57-7cd2e88adc93.png)

I have no customized configurations, just `init` and `up`.

**FYI**: 3.3.7 works very well.

Do you have any idea about it? 🙏

**Comment by harawata** [comment]
Thank you for the report, @kenny-qiao !
I'll look into it as soon as I get some spare time.

**Comment by kenny-qiao** [comment]
@harawata I did some test and found the error came from `Class.forName(driver);` at
```java
public JdbcConnectionProvider(String driver, String url, String username, String password) throws Exception {
  super();
  this.url = url;
  this.username = username;
  this.password = password;
  Class.forName(driver);
}
```

**Comment by h3adache** [comment]
Hi @kenny-qiao thanks for the report!
I can confirm the issue. It looks like it happened when we removed `UnpooledDataSource`.

**Comment by kenny-qiao** [comment]
@h3adache Ah, it is good.
So is there any plan for it, like issue a bug and fix it in next version? 🤔

**Comment by h3adache** [comment]
Yes we will prioritize a fix and release soon as we can!

**Comment by harawata** [comment]
Hi @kenny-qiao ,

@h3adache has already fixed the bug I carefully implemented. ☹️
Could you verify the fix using the latest snapshot?
There is a zip archive in the [snapshot repo](https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/mybatis-migrations/3.3.9-SNAPSHOT/) (please use the newest one if there are many).

**Comment by kenny-qiao** [comment]
@harawata @h3adache Thanks for your quickly fix.

I did a simple test and got error:
![image](https://user-images.githubusercontent.com/23731080/100409902-0f0bc280-30a8-11eb-9ed7-86e74184543d.png)

I think the big issue above has been fixed. But it seems that there is still a problem caused by using `JdbcConnectionProvider` instead of `DataSourceConnectionProvider`. 😢 

Maybe you can re-open this issue. 🙏 

FYI: I am keeping debugging the latest snapshot code. And I will update my progress here if there is.

**Comment by h3adache** [comment]
@kenny-qiao I'm sorry this is my fault.
It was late and I made a mistake refactoring my patch.

**Comment by kenny-qiao** [comment]
@harawata @h3adache 
I have tested both `mybatis-migrations-3.3.9-20201127.164611-2-bundle.zip` and branch `master`.
They all work very well. 🚀 

Thank you guys very much. 👍
