### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by tohagan** [mybatis/migrations#185]
"conneciton" should be "connection".

- ` throw new MigrationException("Error getting conneciton. Cause: " + e, e);`

https://github.com/mybatis/migrations/blob/ea5cf911b5841cd91b516237a637155b1f7bffad/src/main/java/org/apache/ibatis/migration/operations/StatusOperation.java#L77

**Comment by harawata** [comment]
Thank you, @tohagan !
It will be corrected in the next release 3.3.10.
