### ISSUE TITLE
How can I using with mybatis session?

### ISSUE THREAD

**Issue by LazyRichard** [mybatis/migrations#192]
Hi, currently I try to implement runtime schema migration with mybatis and mybatis-migration.

but when I try using migration operation with mybatis sessionFactory but failed.

```java
try (SqlSession session = sessionFactory.openSession()) {
    new UpOperation().operate(new ConnectionProvider() {
        @Override
        public Connection getConnection() {
            return session.getConnection();
        }
    }, migrationLoader, options, stream);
}
```

The error message is like below.

```
Exception has occurred: org.apache.ibatis.migration.MigrationException
"org.apache.ibatis.migration.MigrationException: Error executing command.  Cause: java.sql.SQLException: Error accessing PooledConnection. Connection is invalid."
```

I also tried with `openSession(false)` that is not autocommit session. but then the below error occured.

```
Exception has occurred: org.apache.ibatis.migration.MigrationException
"org.apache.ibatis.migration.MigrationException: Error executing command.  Cause: java.sql.SQLException: Error accessing PooledConnection. Connection is invalid."
```

Current my workaround is create mybatis sessionFactory and create another JdbcConnection for migration.

Is it right way to use mybatis and mybatis-migration sametime??

thanks

**Comment by harawata** [comment]
`ConnectionProvider#getConnection()` needs to return a new connection.
It's better to use `DataSource` directly with the built-in `DataSourceConnectionProvider`.

```java
new UpOperation().operate(new DataSourceConnectionProvider(dataSource), migrationLoader, options, stream);
```

**Comment by harawata** [comment]
Closing.
Let me know if my explanation wasn't clear.
