### ISSUE TITLE
1st migration (for changelog) still shows "pending status" even though the changelog table is created and updated??

### ISSUE THREAD

**Issue by tohagan-tmr** [mybatis/migrations#199]
I am testing code exported by the `migrate script` command.  When I run `migrate up 1` and check `migrate status` it works just fine - records the update in the `RM_CHANGELOG` table as configured in `development.properties`.

However, when I export an SQL script (for our DBA's to run) and test it on the development database it creates the `RM_CHANGELOG`  table and inserts the correct record in the `RM_CHANGELOG` table BUT running `migrate script` shows the status of this migration as as "pending ...". and running `migrate up 1` fails as expected because the table has already been created via exported SQL which confirms that I connected to the same database as `migrate status`. 

### development.properties 
```ini
# Name of the table that tracks changes to the database
changelog=RM_CHANGELOG

## Oracle
send_full_script=false
delimiter=/
full_line_delimiter=true
```

### Code emitted by script command 
```sql
------------------------------------------------------------------------
-- MyBatis Migrations - script
------------------------------------------------------------------------
-- 20211115025530_create_changelog.sql
-- // Creates RM_CHANGELOG Table used to track Rentman DDL & Data changes 

CREATE TABLE RM_CHANGELOG (
  ID NUMERIC(20,0) NOT NULL,
  APPLIED_AT VARCHAR(25) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL
)
/

COMMENT ON COLUMN RM_CHANGELOG.ID IS 'Unique timestamp id of a schema/data change - generated by MyBatis Migrate client.' 
/
COMMENT ON COLUMN RM_CHANGELOG.APPLIED_AT IS 'When change was applied' 
/
COMMENT ON COLUMN RM_CHANGELOG.DESCRIPTION IS 'Change description' 
/

ALTER TABLE RM_CHANGELOG ADD CONSTRAINT PK_RM_CHANGELOG PRIMARY KEY (id)
/

GRANT SELECT,INSERT,UPDATE,DELETE ON RM_CHANGELOG TO RM_SUPERVISOR
/



INSERT INTO RM_CHANGELOG (ID, APPLIED_AT, DESCRIPTION) VALUES (20211115025530, '2021-11-22 15:24:54', 'create changelog')
/

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Mon Nov 22 15:24:54 AEST 2021
-- Final Memory: 8M/483M
------------------------------------------------------------------------
```

## RM_CHANGELOG Table

| ID                          | APPLIED AT                | DESCRIPTION        |
|---------------------|------------------------|----------------------|
| 20211115025530	| 2021-11-22 15:24:54 |	create changelog |

## Status of 1st migration still shows as "pending" ???

```
$ migrate status
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
20211115025530    ...pending...    create changelog   <<< Should not be pending???
20211116104850    ...pending...    col bringup tmp budate
20211116104854    ...pending...    adjust bringup dates residential
20211116145216    ...pending...    drop rm bringup tmp BUDate
```

**Comment by tohagan-tmr** [comment]
After running the 2nd and 3rd migrations ...

```
$ migrate status
------------------------------------------------------------------------
-- MyBatis Migrations - status
------------------------------------------------------------------------
ID             Applied At          Description
================================================================================
20211115025530    ...pending...    create changelog
20211116104850 2021-11-24 11:01:42 col bringup tmp budate
20211116104854 2021-11-24 11:01:42 adjust bringup dates residential
20211116145216    ...pending...    drop rm bringup tmp BUDate
```

**Comment by tohagan-tmr** [comment]
Solved this mystery.  When generating SQL via `migrate script` each INSERT / DELETE to RM_CHANGELOG needs a following COMMIT for Oracle DB with AUTOCOMMIT OFF.   Oracle DB will COMMIT an INSERT or DELETE if it's followed by a DDL statement so some INSERTS worked but the last one failed.  Unsure if a hook event will fix this.  Will try.

```sql
INSERT INTO RM_CHANGELOG (ID, APPLIED_AT, DESCRIPTION) VALUES (20211115025530, '2021-11-22 15:24:54', 'create changelog')
/

COMMIT  ## Missing
/
```

**Comment by tohagan-tmr** [comment]
I'd also like to mentioned that the APPLIED_AT value in invalid since it should reflect the time of the generated SQL script was executed rather than the time the `migrate script` code gen was run.

**Comment by tohagan-tmr** [comment]
Sadly, SQL hooks are NOT included in the code emitted by `migrate script` .

**Comment by harawata** [comment]
As per my previous comment,  I'm going to close this issue.
We plan to release 3.3.10 soon.
