### ISSUE TITLE
If statement in migration scripts?

### ISSUE THREAD

**Issue by Pacane** [mybatis/migrations#20]
Is there any way to use some conditional logic in a migration script? I have 2 databases (hsqlb and postgres) and it seems sometimes their syntax differ. I'd like to run specific parts of migration scripts based on the selected environment.

**Comment by h3adache** [comment]
There is not. There's no plans to support this. Is this something that you can handle with different modules?

**Comment by hazendaz** [comment]
@Pacane Did you get around this issue?  Can this be closed?

**Comment by tohagan** [comment]
You might want to have a look at alternative tools that can support database neutral migrations. 

One I know of FluentMigrator  (you write C# migrations and it generates SQL for the target database).
Supported database are: https://github.com/schambers/fluentmigrator/wiki/Supported-Databases . 
There might be a similar Java tool.

You may still need to SQL platform specific code for Stored procs, Functions, Triggers etc.  I wrote an extension for FluentMigrator to assist doing this in a fork. It allows you to selectively run some scripts for different platforms based on SQL file/folder naming conventions.

**Comment by h3adache** [comment]
Sorry for the slow response. You can do this by combining the scriptpath and env variables as an alternative. It sounds like you already have environments setup for both db vendors, you can setup script paths separately for them as well.
This feature was added a while back but isn't documented in the help/online docs I'm afraid. I'll add a ticket for that

**Comment by h3adache** [comment]
#64 was created
