### ISSUE TITLE
BUG: `migrate script`: 1st migration rollback will always fail due to invalid DELETE statement 

### ISSUE THREAD

**Issue by tohagan-tmr** [mybatis/migrations#201]
The first migration creates the CHANGELOG table correctly drops that table when you rollback (Undo).  However, if you emit SQL script using `migrate script --some-number-- 00000000000000 > rollback01.sql` for this 1st migration, the rollback code includes a DELETE statement on the CHANGELOG table that will fail because the CHANGELOG has just been dropped.

**Comment by harawata** [comment]
You are right ... but I'm not sure what you expect to happen.
If you need to `migrate down` the first migration, maybe you should create the changelog table in `bootstrap.sql` rather than in the first migration script.

**Comment by tohagan-tmr** [comment]
Currently it's emitting
```sql
DROP CHANGGELOG   << Added by migration

DELETE .... FROM CHANGELOG  <<< Added by "migrate script" - BUG 
```

So ... what I'm suggesting is that the code in `migrate script` that emits this DELETE statement just need to have a condition that checks if it's the 1st migration and in this instance avoids emitting the DELETE statements.

**Comment by tohagan-tmr** [comment]
I've had a closer look at the code and I can see that it would likely need to replace reading migration files using buffers with either reading the whole file or a line at a time so you can reliably search for a line containing "DROP TABLE ${changelog};".

**Comment by harawata** [comment]
I would like to avoid searching a particular string in a file.
How about omitting the `INSERT` when the first migration script's description is 'create changelog'?

**Comment by tohagan-tmr** [comment]
Yeah sure ... that might be simpler!
