### ISSUE TITLE
BUG/Feature?: `migrate script` : SQL hooks are NOT included in emitted SQL code. 

### ISSUE THREAD

**Issue by tohagan-tmr** [mybatis/migrations#203]
I found that when using this setting in `development.properties` ... 

```ini
hook_after_each_up=SQL:after-each-up.sql
hook_after_each_down=SQL:after-each-down.sql
```

The SQL in `after-each-up.sql` and `after-each-down.sql` was correctly executed when running `migrate up` and `migrate down` but was excluded from code emitted by `migrate script`.  

I'd recommend this feature be added and enabled via an option in `.*properties` files such as `hook_sql_scripts_enabled=true` which would be `false` by default for backward compatibility in case existing projects don't wish / expect this to code be emitted. I think it's reasonable to assume that non-SQL hooks are always ignored.

**Comment by harawata** [comment]
Hello @tohagan-tmr ,

#199 seems like a good use case for this enhancement (i.e. append `COMMIT` call after inserting changelog entry).
The implementation will be significantly different from the existing hooks, so give me some time to think about it.
