### ISSUE TITLE
Feature: redo command (like Rails db:migrate:redo)

### ISSUE THREAD

**Issue by tohagan-tmr** [mybatis/migrations#205]
Please add a `migrate redo` command so that ...

    $ migrate redo       

... runs `migrate down 1` and if that succeeds it runs `migrate up 1` and ...

    $ migrate redo 3 

... runs `migrate down 3` and if that succeeds it runs `migrate up 3`

   
I know, I know .... I've asked a lot this week!  But I think this would be a great addition and should be dead easy to implement. 

I've recently been using Ruby of Rails which was the one of the first (I think **the first**) frameworks to support DB migrations. They support a `rails db:migrate:redo` ([ref](https://edgeguides.rubyonrails.org/active_record_migrations.html#rolling-back)) command. I found this is very convenient when coding as I'm constantly typing the two commands. I can just write my own shell script to do the same but I think it really it belongs with the migrate command.

**Comment by tohagan-tmr** [comment]
Here's the equivalent Bash function ...

```bash
function migrate_redo() {
  n="${1-1}"
  migrate down "$n" && migrate up "$n"
}
```

**Comment by tohagan-tmr** [comment]
Thank you !!

**Comment by harawata** [comment]
I actually do the down-then-up a lot, so thank you for the request! :)
