### ISSUE TITLE
missing bin file in .zip file

### ISSUE THREAD

**Issue by musserjw** [mybatis/migrations#21]
I just downloaded the zip and followed the instructions in the readme file.  It references a bin folder in the zip, but one doesn't exist.  Is the readme outdated, or am I just missing something.

**Comment by harawata** [comment]
Which .zip file are you referring to?
The latest one (3.2.0) on the release page contains the bin directory correctly.
https://github.com/mybatis/migrations/releases

**Comment by musserjw** [comment]
Didn't see the releases link.  I was just going off of the one on the front page.  Thank you very much.

**Comment by harawata** [comment]
You are welcome :-)
