### ISSUE TITLE
Does MyBatis Migrations work with ParAccel?

### ISSUE THREAD

**Issue by amrit7** [mybatis/migrations#23]
Hi,

I'm using ParAccel and I cannot run: migrate status

-- MyBatis Migrations FAILURE
-- Total time: 0s
-- Finished at: Wed Jul 22 17:15:03 BST 2015
-- Final Memory: 5M/480M

ERROR: Could not create SqlRunner. Cause: java.sql.SQLException: Error setting driver on UnpooledDataSource. Cause: java.lang.ClassNotFoundException: paraccel-jdbc.jar

Environment File contains
JDBC connection properties.
driver=paraccel-jdbc.jar

I'm using Actian's ParAccel JDBC driver: 
           http://esd.actian.com/product/Matrix_Drivers/JDBC/java/

Does MyBatis Migrations support ParAccel?

**Comment by h3adache** [comment]
Give the full path to the jdbc jar.

**Comment by amrit7** [comment]
Hi,

thanks - I've now given full path to JDBC - now the error:

ERROR: Could not create SqlRunner. Cause: java.sql.SQLException: Error setting driver on UnpooledDataSource. Cause: java.lang.IllegalArgumentException: name

**Comment by h3adache** [comment]
I'm sorry I didn't mean in driver. I meant specify a driver_path.
Or just drop your driver into the correct location.
Please read http://mybatis.github.io/migrations/init.html

**Comment by amrit7** [comment]
Hi,

I'm still getting:
ERROR: Could not create SqlRunner. Cause: java.sql.SQLException: Error setting driver on UnpooledDataSource. Cause: java.lang.ClassNotFoundException: paraccel-jdbc.jar


I'm using Actian's ParAccel JDBC driver: 
http://esd.actian.com/product/Matrix_Drivers/JDBC/java/


I had been through http://mybatis.github.io/migrations/init.html
I already applied the init command, so have the appropriate subfolders: drivers, environments, scripts.

I copied the .jar file into the driver subfolder: paraccel-jdbc.jar - default, so did not specify the driver_path variable.

 Environment file: development.properties has the entry:
          driver=paraccel-jdbc

 1) should this have this extension .jar? For example: driver=paraccel-jdbc.jar
I tried with and without the extension, neither is working.
		   
		   
2) For MyBatis - does it matter what the name of the driver filename is called? Notice the hypen in the filename (paraccel-jdbc.jar).
		
3) To Install the driver appropriately, I added the full driver path to the CLASSPATH environment variable.
		   CLASSPATH=C:\MyBatis\~\drivers\paraccel-jdbc.jar
		   
Is this required? It does not work, with or without the CLASSPATH entry.
		
Thanks

**Comment by amrit7** [comment]
This issue is not Closed.

**Comment by h3adache** [comment]
Not to be rude but 2 seconds of [googling](https://www.aquaclusters.com/app/home/project/public/aquadatastudio/wikibook/Documentation14/page/305/ParAccel-Analytic-Platform-JDBC-Drivers) told me that you are using the wrong name for the driver. I don't know what version of paraccel you are using but my guess is that the above is the correct driver to use.
I suggest you use the [mailing list](http://mybatis.github.io/mybatis-3/mail-lists.html) as issues is not a tech support forum.

**Comment by amrit7** [comment]
I have seen that page - but that is for the Aqua Data Studio product.

In terms of looking at the Aqua Data Studio page - this is showing the DRIVER CLASS:
![driver2](https://cloud.githubusercontent.com/assets/13454662/8855489/4efa90ce-315d-11e5-9d90-7c805532004d.JPG)

The name of the driver is paraccel-jdbc.jar - the same as what you have shown in the Aqua Data Studio page.
![driver3](https://cloud.githubusercontent.com/assets/13454662/8855567/b5677994-315d-11e5-9856-02fa38242be6.JPG)

The driver version is what I'm using is below:
![driver](https://cloud.githubusercontent.com/assets/13454662/8855423/f8537736-315c-11e5-942c-41a8ffdd1d4e.JPG)

It's not clear, when you say the wrong name of the driver - what should I be using for the name of the driver?

**Comment by amrit7** [comment]
it's working now.. .

driver=com.paraccel.Driver

this wasn't clear - thought it should be filename of the driver. 

Closed

**Comment by h3adache** [comment]
JDBC driver is always the class of the driver.
The jar is just the packaging. It's just how java and JDBC work to find the driver.  
Watch this [video by @cbegin](https://www.youtube.com/watch?v=c45AevIuYGk).
It shows iBatis but the instructions have not changed

**Comment by amrit7** [comment]
Thanks for this

-------- Original message --------
