### ISSUE TITLE
Facing issues with delimiter while running mybatis migrations which contains procedures

### ISSUE THREAD

**Issue by chiruyarabolu** [mybatis/migrations#232]
Hello Team,

Facing issues with delimiter as the procedures syntax has multiple ";" which we used as delimiter 

for example,

create or replace PROCEDURE MYBATISTEST
****code****
ORDER BY ****;
END;

The issue here is because of ";" before the END, it is taking it as a separate line and END; as a separate line.

Which is not creating the procedure properly.

Please let me know if there is any solution to it.

**Comment by harawata** [comment]
Hello @chiruyarabolu ,

You can change the delimiter using a special syntax `-- @DELIMITER`. e.g.

```sql
-- @DELIMITER $
create or replace PROCEDURE MYBATISTEST
code
ORDER BY ****;
END;
$
-- @DELIMITER ;
```

**Comment by chiruyarabolu** [comment]
Thanks a lot this fixed the issue
