### ISSUE TITLE
Warning: Missing migration script

### ISSUE THREAD

**Issue by chiruyarabolu** [mybatis/migrations#233]
Everytime I run migrate up, when there is a success it is showing up Warnings as below

WARNING: Missing migration script. id='20220609064216', description='Oraclemigrate'.
WARNING: Missing migration script. id='20220609064219', description='Oraclemigrate'.
WARNING: Missing migration script. id='20220609064220', description='ServiceLayermigrate'.

And it is piling up everytime 

Anyway to remove these warnings?

**Comment by harawata** [comment]
That error tells you that those script files are removed after they are applied to the database.
This should not happen, you know.

The correct way to resolve the warnings would be to restore the deleted migration script files in the 'scripts' directory.
If, for some reason, the changes applied by those scripts can be safely ignored, deleting the corresponding rows in the changelog table may also resolve the warnings.
