### ISSUE TITLE
Issues while creating changelog table

### ISSUE THREAD

**Issue by chiruyarabolu** [mybatis/migrations#234]
I am facing the below error while using MIGRATE UP command. It is not creating the changelog table

-- // Create Changelog

-- Default DDL for changelog table that will keep
-- a record of the migrations that have been run.

-- You can modify this to suit your database before
-- running your first migration.

-- Be sure that ID and DESCRIPTION fields exist in
-- BigInteger and String compatible fields respectively.

CREATE TABLE CHANGELOG (
ID NUMERIC(20,0) NOT NULL,
APPLIED_AT VARCHAR(25) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL
);

ALTER TABLE CHANGELOG
ADD CONSTRAINT PK_CHANGELOG
PRIMARY KEY (id);

Error executing: -- // Create Changelog

-- Default DDL for changelog table that will keep
-- a record of the migrations that have been run.

-- You can modify this to suit your database before
-- running your first migration.

-- Be sure that ID and DESCRIPTION fields exist in
-- BigInteger and String compatible fields respectively.

CREATE TABLE CHANGELOG (
ID NUMERIC(20,0) NOT NULL,
APPLIED_AT VARCHAR(25) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL
);

ALTER TABLE CHANGELOG
ADD CONSTRAINT PK_CHANGELOG
PRIMARY KEY (id);

.  Cause: java.sql.SQLSyntaxErrorException: ORA-00922: missing or invalid option

Any ways to fix this?

**Comment by harawata** [comment]
Hello @chiruyarabolu ,

Try...

```
send_full_script=false
```

The right value for this setting depends on the driver.

**Comment by chiruyarabolu** [comment]
Thanks
