### ISSUE TITLE
Need to set Line Separator 

### ISSUE THREAD

**Issue by ebreeze** [mybatis/migrations#268]
I am trying to use scriptRunner from CF with MSSQL scripts as follows:

```
scriptRunner.setSendFullScript(true);
scriptRunner.setAutoCommit(false);
scriptRunner.setStopOnError(true);
scriptRunner.setRemoveCRs(false);
scriptRunner.setFullLineDelimiter(true);
scriptRunner.setDelimiter("GO");
scriptRunner.setEscapeProcessing(true);
scriptRunner.runScript(local.bufferedReader);
```

With some of the scripts it works fine, but wherever a "GO" appears somethere in the script comes an exception, because it seems like all of the new lines get removed and all the lines get merged.

Seems like LINE_SEPARATOR is an empty string.

I think adding the possibility to specify the line separator would be a solution in my case:

`scriptRunner.setLineSeparatir("\n\r");`

and I think it would no be difficult to add.

**Comment by harawata** [comment]
Hello @ebreeze ,

If you want use `ScriptRunner` outside of Migrations, please copy and modify it so that it satisfies your requirements.
It does not depend on Migrations nor MyBatis core, so there should be no difficulty.
People love this class for some reason, but it's designed to be an internal utility.

**Comment by hazendaz** [comment]
@ebreeze Line separator on this class is using java's system.lineSeparator so this sort of indicates if that is an issue there that its corrupted to java itself, possibly wiped out on your setup maybe which would cause that issue.

@harawata Somewhat related, in the migrator code there is usage of separate get from system that cannot use line separator properly as unit tests are manipulating it heavily.  That too could be issue here that its being forced to be changed during usage in this particular case and that won't work.  I'm going to look at this a bit more as it would seem we have some need to manipulate that and it would be better to use standard practices in general so maybe exposing it to override in both cases might be a good idea.  Anyway, looking at that some...

**Comment by harawata** [comment]
@hazendaz ,
Thank you for taking a look!
If there is a better way, I'm all for it.

Just to be clear, `System.setProperty("line.separator", "...");`  is effective only in that particular process and does not affect other JVM. It's not like the setting is stored somewhere in system.

**Comment by harawata** [comment]
@ebreeze 

As you can [see](https://github.com/mybatis/migrations/blob/master/src/main/java/org/apache/ibatis/migration/operations/ScriptRunner.java#L35), `LINE_SEPARATOR` is just a constant holding the value returned from `System.lineSeparator()`.
So, it's highly unlikely that `LINE_SEPARATOR` is an empty string and if it actually is, it must be a JDK bug.

If you could share an example file that is causing the problem, I would take a look.

**Comment by ebreeze** [comment]
Yes, it seems like the problem is in the Java (JDK) Environment itself, but I am afraid this is not something I could change.

Here is a test.sql file
[test.zip](https://github.com/mybatis/migrations/files/10132266/test.zip)

**Comment by harawata** [comment]
I should have mentioned that you can change the delimiter inside a script using a special command.
Assuming that you didn't change the default delimiter (i.e. `;`), the following script may be executed successfully.

```sql
-- @DELIMITER GO

SET XACT_ABORT ON;

BEGIN TRAN;

	SELECT
		*
	FROM
		INFORMATION_SCHEMA.VIEWS
	WHERE
		TABLE_SCHEMA = 'custom'
		AND TABLE_NAME = 'mytest';

GO

-- @DELIMITER ;

COMMIT TRAN;
```

`-- @DELIMITER` is a special command of Migrations just like `GO` is a special command only recognizable in `sqlcmd`, etc..
