### ISSUE TITLE
Runtime error when migrate up for the default create_changelog.sql

### ISSUE THREAD

**Issue by superbull** [mybatis/migrations#36]
I setup the Mybatis migration by following the documentation. After run `migrate up` there is a `com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException`.

I found this stackoverflow topic: http://stackoverflow.com/questions/23000085/mybatis-migrations-migrate-up-causes-org-apache-ibatis-jdbc-runtimesqlexception

The solution is change the default environment setting of `send_full_script` from
```
send_full_script=true
```
 to 

```
send_full_script=false
```

My question is: **If the default migration script do not work with the default setting, why set the `send_full_script` to `true` by default?**

**Comment by rponte** [comment]
Sending full script just works for some JDBC drivers. Probably your driver
does not support it.

If I'm not wrong there's a comment in the properties file explaining about
it.
On ter, 2 de fev de 2016 at 22:58 Deng Zhi Cheng <notifications@github.com>
wrote:

> I setup the Mybatis migration by following the documentation After run migrate
> up there is a commysqljdbcexceptionsjdbc4MySQLSyntaxErrorException
>
> I found this stackoverflow topic:
> http://stackoverflowcom/questions/23000085/mybatis-migrations-migrate-up-causes-org-apache-ibatis-jdbc-runtimesqlexception
>
> The solution is change the default environment setting of send_full_script
> from
>
> send_full_script=true
>
> to
>
> send_full_script=false
>
> My question is: *If the default migration script do not work with the
> default setting, why set the send_full_script to true by default?*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mybatis/migrations/issues/36>.
>
-- 
Rafael Ponte
TriadWorks | Formação Java
http://cursos.triadworks.com.br

**Comment by superbull** [comment]
Yes, so I think the default setting should works for most JDBC drivers. That is set the default value of `send_full_script` to `false` in the template file.

**Comment by hazendaz** [comment]
@superbull I believe this was a usage issue per notes above.  I don't think there is anything to do here.  Can you confirm so I can close this out?  If something is needed, please let me know.

**Comment by harawata** [comment]
@superbull 
I am not sure which is appropriate as the default, but changing the default could break existing solutions.
