### ISSUE TITLE
ToolProvider implementation

### ISSUE THREAD

**Issue by bowbahdoe** [mybatis/migrations#388]
I am making a little project where I am giving CLI interfaces a Java api: https://github.com/bowbahdoe/tools

The glue is that if a tool provides an implementation of `ToolProvider` then I can dynamically find it and run it without having
to spawn a new JVM. `ToolProvider.findFirst("javac");` would give me an interface to javac, for example.

I would like to make one for this, but for that I would want to make a submodule where I bring this in as a dependency
so that there aren't any system level `sdk install`s folks need to do. And for that i'd need this project to 

1. Have a proper module-info
2. Provide an implementation of `ToolProvider` (will require being able to run things without a wild `System.exit` + threading through provided `out` streams over `System.out`)
3. Declare that `ToolProvvider` as being provided in the module-info + META-INF/services (just in case, i guess?)

**Comment by harawata** [comment]
Hello @bowbahdoe ,

If it can be done in a separate repo, go for it! 🚀
If it has to be done in this repo, I would rather not add extra dependency.

**Comment by bowbahdoe** [comment]
It can't be done in a separate repo because it will require at least a few internal changes to have System.out/err be configurable, System.exit isn't called, etc. 

But it wouldn't be a dependency. It's "java.util.spi.ToolProvider", not a class from a random library

**Comment by harawata** [comment]
Sorry about my misunderstanding!

So, we have to make those changes to make this tool (migrations) compatible with your tool, is that correct?
We may add `module-info.java` eventually, but I cannot say I am interested in other changes at this point.

p.s.
I'm not exactly sure what "giving CLI interfaces a Java api" means, but if you are looking for a way to perform migrations from within a Java app, the runtime migration might be helpful.
https://mybatis.org/migrations/runtime-migration.html

**Comment by bowbahdoe** [comment]
So just for color: If you run `javac -d whatever ...` that spins up the JVM, compiles the specified code, and then the JVM shuts down.

If you call `javac` through the tool provider it looks like this.

```
var toolProvider = ToolProvider.findFirst("javac").orElseThrow();
toolProvider.run(System.out, System.err, new String[] { "-d",  "..." });
```

And you can reuse the same JVM for multiple calls.

So our two ways of calling a CLI are via subprocess or via tool provider. Whenever tool provider is an option its preferable because it can come in as purely a maven dependency - no "download this folder, add it to your path."

It is an admittedly minor benefit, but this is the sort context I want to slot `migrate` into.

```

    @CommandLine.Command(name = "compile")
    public void compile() throws ExitStatusException {
        clean();
        Javac.run(arguments -> {
            arguments
                    ._d(Path.of("build/javac"))
                    .__module_path("libs")
                    .__module_source_path("./modules/*/src")
                    ._g()
                    .__release(21)
                    .__module(
                            "web.hello",
                            "web.util",
                            "web.hello.test",
                            "web.util.test"
                    );
        });
    }

    @CommandLine.Command(name = "package")
    public void package_() throws ExitStatusException {
        compile();
        Jar.run(arguments -> {
            arguments
                    .__create()
                    .__file(Path.of("build/jar/web.hello.jar"))
                    .__main_class("web.hello.Application")
                    ._C(Path.of("modules/web.hello/res"), ".")
                    ._C(Path.of("build/javac/web.hello"), ".");
        });

        Jar.run(arguments -> {
            arguments
                    .__create()
                    .__file(Path.of("build/jar/web.util.jar"))
                    ._C(Path.of("build/javac/web.util"), ".");
        });

        Jar.run(arguments -> {
            arguments
                    .__create()
                    .__file(Path.of("build/jar/web.hello.test.jar"))
                    ._C(Path.of("build/javac/web.hello.test"), ".");
        });

        Jar.run(arguments -> {
            arguments
                    .__create()
                    .__file(Path.of("build/jar/web.util.test.jar"))
                    ._C(Path.of("build/javac/web.util.test"), ".");
        });
    }
``` 

Where for each of these CLI tools I built on top of (interchangeably) `ToolProvider` or `ProcessBuilder` a small api where
there are methods corresponding to each CLI argument.

The reason I am exploring this road is because I think that, in an education context, having knowledge you learned about the CLI be directly transferrable to making a build script and vice-versa is valuable. All these lines of code even print out what command is being run before executing. If you did it wrong you should be able to copy paste the command, tweak it in the cli, and translate those tweaks back to Java smoothly.

What that allows us to pull off is something like

```
// Code here
Tool.ofToolProvider("migrate").run("up);
// Code here
```

To be brought in as a maven dep. For things that don't work like this I provide an API for someone to download the tool.

```
    @CommandLine.Command(name = "install_tools")
    public void installTools() throws Exception {
        GoogleJavaFormat.downloadVersion("1.23.0", GOOGLE_JAVA_FORMAT_JAR);
        PMD.downloadVersion("7.4.0", PMD_PATH);
    }
```

Then wherever they put it needs to be threaded through at runtime. 

```
    @CommandLine.Command(name = "format")
    public void format() throws Exception {
        var files = javaFiles();
        GoogleJavaFormat.run(
                GOOGLE_JAVA_FORMAT_JAR,
                arguments -> {
                    arguments
                            .__aosp()
                            .__replace()
                            .files(files);
                }
        );
    }

    @CommandLine.Command(name = "lint")
    public void lint() throws Exception {
        var files = javaFiles();
        PMD.run(PMD_PATH, arguments -> {
            arguments.add("check");
            arguments.__rulesets("ruleset.xml")
                    ._r(BUILD_PATH.resolve("pmd/report.txt"))
                    .__cache(BUILD_PATH.resolve("pmd/cache"))
                    .__dir(files);
        });
    }
```
    
And like for the PMD example I am looking in the downloaded folder, finding `bin`, then picking between `pmd` and `pmd.bat` based on their OS. This is what i'd need to do for migrate right now too. That or rely on them installing it on
their path separately.

So like, the sky isn't falling. If you aren't interested in doing the stuff to make `toolProvider.run(System.out, System.err, new String[] { "..." });` not exit the JVM and pipe to what someone provides that makes sense; i would have opened a PR myself if it was immediately obvious how to do it.

But thats what i mean by "giving CLI interfaces a Java API". Quite literally methods to call that map 1-1 to the CLI interface.

**Comment by harawata** [comment]
Thank you for the explanation, @bowbahdoe !

The idea is interesting, but considering the target usage of migrations, I don't think it benefits many users.
We might reconsider at some point, but for now, I have to say "no", I am afraid.
I hope you find other CLI commands that fit your tool better.

**Comment by bowbahdoe** [comment]
Totally fair - do consider adding that module-info though

**Comment by harawata** [comment]
I'm still not familiar with JPMS (testing looked tricky), but we should probably reorganize package structure if we were to add `module-info.java`, I think.
Anyway, thank you again for taking the time to submit the request!
