### ISSUE TITLE
extend script command

### ISSUE THREAD

**Issue by step307** [mybatis/migrations#4]
Enhancement proposal:

New mode for command "script" to generate a script for all pending migrations (similar to up)

Could be "migrate script" without version given or "migrate script up"

**Comment by hazendaz** [comment]
@jollyblade Is this something you could still put together?  There has been a ask to release updated version of migrations but there are no real changes in a number of years so I'm trying to see if we can get some issues addressed so the release actually is worthwhile :)

**Comment by harawata** [comment]
Fixed as #29.
