### ISSUE TITLE
Need a way to configure multiple Database schemas

### ISSUE THREAD

**Issue by jmodi1982** [mybatis/migrations#40]
Hi,

We have 1 database with multiple schema (~250) and we would be tracking and deploying changes to all the 250 schema. Since the 250 schema have different credentials, how do we setup environment properties to enable mybatis migrations to work.

**Comment by jmodi1982** [comment]
We found a way to create to multiple schemas using proxy user. Setup a proxy user and use it in the environments file

**Comment by harawata** [comment]
Cool! Thank you for sharing! :smile:
