### ISSUE TITLE
Display Result Set

### ISSUE THREAD

**Issue by syryin** [mybatis/migrations#43]
Hi,
For the command "up" and "pending" in command line, executed SQL message/result is not displayed. It says only "MyBatis Migrations SUCCESS"

**Comment by jmodi1982** [comment]
Yes, even i have faced this issues. we would also like to see message "10 rows inserted", "1 table dropped" similar to what we get in Toad or SQL Developer studio.

How can we enable something like this basically the error messages from SQL

**Comment by h3adache** [comment]
Is this using migrations install or maven/grade plugin?

**Comment by jmodi1982** [comment]
i am running simple migration up command from cmd line and not able to see result of the SQL executed as confirmation like "10 rows inserted", "1 table dropped" , instead I see following message - 
-- MyBatis Migrations SUCCESS
-- Total time: 1s
-- Finished at: Thu May 05 12:09:16 CDT 2016
-- Final Memory: 47M/479M

Is there a way we can show the results coming back after SQL execution ?

**Comment by harawata** [comment]
Here is my output.
I am on MySQL

**Comment by h3adache** [comment]
I have the same output as @harawata on both mysql and sql server. Can you please show us your output and a sample project?

**Comment by h3adache** [comment]
Hi @jmodi1982 I'm closing this due to lack of feedback and the fact that we can't reproduce it but please reopen if you still see this.
