### ISSUE TITLE
Pre/Post condition hooks

### ISSUE THREAD

**Issue by tohagan** [mybatis/migrations#60]
We provide scripts that execute SQL queries that act as Pre/Post conditions on the data.  Each script contains a query. If the query returns any data then the Pre or Post condition has failed. The query output should identify the cause.

These query scripts are not migrations but very useful in the data migration process. You want another directory / hook for each of these.  

They can simplify complex migration cases by making data value assumptions that need to be asserted on production data prior to being applied.  They can also keep the data much cleaner by post checking that data migrations were correctly applied or that the database remains in a "clean and valid " state.

**Comment by harawata** [comment]
I am not sure if I understand the use case correctly, but it sounds like another use case of migration hooks.
In a hook script, you can get the ID and the description of a migration, so it is possible to perform tasks specific to a particular migration.

```js
if (hookContext.getChange().getId() == "20161027102930") {
  // ...
}
// or...
if (hookContext.getChange().getDescription().contains("__DATA__")) {
  // ...
}
```

It is also possible to abort migration process by throwing an exception from within a hook (it does not rollback changes already applied, though).

**Comment by h3adache** [comment]
http://www.mybatis.org/migrations/hooks.html
