### ISSUE TITLE
Feature: Allow/Disallow empty UNDO clause for DOWN

### ISSUE THREAD

**Issue by tohagan** [mybatis/migrations#61]
When a migration should not be undone, I typically just remove the `-- //@UNDO` line so that `migrate down` will fail for this migration. This is what you want when using the migration in production .

However, for development you'd prefer to just ignore the empty undo and execute nothing on the assumption that you'll soon perform a `migrate up`.  

To configure this behaviour for production and development environments, I'm recommending that you add a new boolean property to that will either allow or disallow empty UNDO's for `migrate down`.

**Comment by harawata** [comment]
Hi @tohagan ,

Which DB are you using?
With a migration script with no `-- //@UNDO` line, `migrate down` seems to succeed on MySQL.

```
------------------------------------------------------------------------
-- MyBatis Migrations - down
------------------------------------------------------------------------
========== Undoing: 20160506152243_insert.sql ==================================

------------------------------------------------------------------------
-- MyBatis Migrations SUCCESS
-- Total time: 0s
-- Finished at: Fri Nov 18 02:03:15 JST 2016
-- Final Memory: 15M/479M
------------------------------------------------------------------------
```

Besides, the feature you describe is basically what `--force` option does.
For example, if an UNDO part contains some statement that is known to fail, `migrate down` will fail whereas `migrate down --force` will succeed.

**Comment by tohagan** [comment]
Thanks. I didn't spot the --force option.

**Comment by harawata** [comment]
You're welcome :)
