### ISSUE TITLE
bootstrap not working with more than one table

### ISSUE THREAD

**Issue by jingyou** [mybatis/migrations#66]
if more than one table is defined in bootstrap.sql file, the bootstrap command will throw SQLSyntaxErrorException.

Here's an example:

-- begin of the bootstrap.sql file
CREATE TABLE card_type (
    ID BIGINT(20)
);

CREATE TABLE card (
    ID BIGINT(20)
);

-- end of the bootstrap.sql file

**Comment by harawata** [comment]
Assuming you are using MySQL, send_full_script must be set to false in the environment properties.

**Comment by harawata** [comment]
Assuming `send_full_script=true` resolved the problem.
