### ISSUE TITLE
$MIGRATION_HOME or $MIGRATIONS_HOME?

### ISSUE THREAD

**Issue by evandroamparo** [mybatis/migrations#68]
The installation instructions tell the environment variable for the installation folder is MIGRATION**S**_HOME but ```migrate init``` looks for $MIGRATION_HOME/migration.properties.

When I tried to use a custom prefix I realized that I had to create a new environment variable. Is there a reason for that? Could it be unified into a single variable?

**Comment by harawata** [comment]
The correct variable name is `MIGRATIONS_HOME`.
I searched the text `MIGRATION_HOME` in the project and it only exists in a few doc files and is never used in the actual code.
I'll fix the doc files later.

Thanks for the report!

**Comment by evandroamparo** [comment]
I imagined it was an error in the docs and did it by just saving the file in $MIGRATIONS_HOME.
