### ISSUE TITLE
Variable substitution does not work in custom templates

### ISSUE THREAD

**Issue by evandroamparo** [mybatis/migrations#69]
I'm trying to configure my own template for new migrations but I don't see how to include a placeholder for the description.
In the file https://github.com/mybatis/migrations/blob/b4e2f982b6e504a13a788fc0d8cbc8e02805901b/src/main/java/org/apache/ibatis/migration/template_migration.sql#L17 there is a ```${description}``` parameter but it doesn't work for custom templates.

**Comment by harawata** [comment]
Hi @evandroamparo ,

Thanks for the report!
It should be fixed in the latest 3.3.0-SNAPSHOT.

**Comment by evandroamparo** [comment]
Thank you.
