### ISSUE TITLE
Feature request: expand the usage of hooks (JSR-223 and SQL) to all migration commands

### ISSUE THREAD

**Issue by sjanssens1977** [mybatis/migrations#71]
In my search for a solution to manage test data using MyBatis Migrations I stumbled upon the hooks feature.

I managed to implement a solution by which I use the [before|after]_each_[up|down] hooks to temporary replace a script which contains test data insert statements with an script containing no sql statements.
This implementation works great if you use the up and down commands to manage each environment.

Because of certain regulations the production environment needs to be maintained using plain old sql files.
Unfortunately the hooks feature only works for the commands up and down.
This means, in my case, that a script, generated by the script command on the same set of migration scripts for the same environment, after execution, will result in a different database compared to using the up command.

Therefore I would like to ask if the hooks feature could also be expanded to the other commands: script, version, pending.

The solution is simple and just needs 3 files (do not forget to change the file extension to .sql and .js)
[empty_migration_script.txt](https://github.com/mybatis/migrations/files/964502/empty_migration_script.txt)
[post-process.txt](https://github.com/mybatis/migrations/files/964503/post-process.txt)
[pre-process.txt](https://github.com/mybatis/migrations/files/964504/pre-process.txt)

Regards,
Steven Janssens.

**Comment by harawata** [comment]
Hi @sjanssens1977 ,

I'm sorry for a late reply!

`version` and `pending` are special cases of `up`/`down`, so it makes sense to apply hooks when executing these commands.
I will look into it.

Regarding `script` command, though, applying hook seems inappropriate.
Executing SQL hook on every execution of `script` command may not be what users expect, for example.

In your case, the recommended solution would be to store the environment-dependent DML scripts (i.e. test data insert statements) in a separate directory than DDL scripts.
Here is an example directory structure.

```tree
MIGRATION_HOME
├── drivers
├── environments
├── hooks
├── scripts
│   ├── 001_create_changelog.sql
│   ├── 002_first_migration.sql
│   └── 003_second_migration.sql
└── testdata
    ├── 002.sql
    └── 003.sql
```

The idea is to insert test data using hook in non-production environment.
In the example above, `002.sql` will be executed after `002_first_migration.sql` is applied.
The after-each-up script would look something like this (not tested).

```js
var Files = Java.type("java.nio.file.Files");
var Paths = Java.type("java.nio.file.Paths");
var String = Java.type("java.lang.String");
var StandardCharsets = Java.type("java.nio.charset.StandardCharsets");

var path = Paths.get(migrationPaths.getBasePath()
  + "/testdata/" + hookContext.getChange().getId() + ".sql");
if (Files.exists(path)) {
  var query = String.join("\n",
    Files.readAllLines(path, StandardCharsets.UTF_8));
  hookContext.executeSql(query);
}
```

`script` command does nothing special.

The above script is taken from this Japanese [blog entry](https://pinzolo.github.io/2016/11/17/hook-in-mybatis-migrations-330-snapshot.html) written by a user who had a similar requirement as yours.

**Comment by harawata** [comment]
Hooks are now applied to 'version' and 'pending' (#71).
