### ISSUE TITLE
ERROR: Error copying org/apache/ibatis/migration/template_README on Mac

### ISSUE THREAD

**Issue by orlanthi** [mybatis/migrations#72]
Steps:
1. mkdir db
2. mybatis-migrations-3.3.0/bin/migrate --path="$(pwd)/db" init

Result:
ERROR: Error copying org/apache/ibatis/migration/template_README to /some/path/db/README.  Cause: java.io.FileNotFoundException: file:/some/path/mybatis-migrations-3.3.0/lib/mybatis-migrations-3.3.0.jar!/org/apache/ibatis/migration/template_README (No such file or directory)

**Comment by harawata** [comment]
Thanks for the report, @orlanthi .
As this is a blocker issue, I'll release 3.3.1 as soon as possible.
