### ISSUE TITLE
Migrate fail when postgreSQL issue a Notice

### ISSUE THREAD

**Issue by jpenalver10** [mybatis/migrations#84]
Hello,

i'm currently upgrading Mybatis Migrations from 3.2.0 to last release 3.3.1 in order tu use Hooks, in combination with Java 1.8.0_73 and PostgreSQL 9.5.

I've some scripts that, in order to re-execute without problems, have some initialization SQL code like:

  `DROP TABLE IF EXISTS FOO`

According to PostgreSQL documentation (https://www.postgresql.org/docs/9.5/static/sql-droptable.html) IF EXISTS not throw an error if the table does not exist, throw a **Notice** (similar to warning), like this:

`NOTICE: table "Foo" does not exist, skipping`

With migrations version 3.3.1, when database raise this Notice, mybatis abort the execution and no execute scripts.

With migrations 3.2.0 the scripts runs well, but i cant use Hooks.

Any notice about this?

Thanks, best regards.

**Comment by harawata** [comment]
Hi @jpenalver10 ,

Since 3.3.0, Migrations stops on warnings as you noticed.
The change was made because Oracle throws a warning on procedure compilation error (see #46).

You should be able to prevent PostgreSQL from raising the warning by setting `client_min_messages` to 'error' (the default is 'notice') before executing the statement with `IF EXISTS`.
I haven't tested it myself, so please let me know if it didn't work.

**Comment by jpenalver10** [comment]
Aha ok, 

yes i've tested before write the question, its work, but I do not think it's a good idea to mix my database model scripts with this implementation detail.

An option would have been only stops with this oracle warnings for not to lose backward compatibility.

In our CI environment, the scripts are made by developers, that only knows application logic (create tables, etc...), not knows infrastructure details.

Its possible fix this problem?

**Comment by harawata** [comment]
I guess we may need a new environment option to ignore warnings.
As it's safer for Oracle users, the default behavior is to stop migration on warnings and you may have to modify the .properties file.
Does it sound reasonable?

**Comment by jpenalver10** [comment]
yes!!! I think it's a good solution!

We wait impatiently the new release!

Thank you so much!!!

**Comment by jpenalver10** [comment]
Hi @harawata !

When you estimate that can add this feature to a new release?

the intenttion of this question is only for planning my tasks.

Thanks!

**Comment by harawata** [comment]
Hi @jpenalver10 ,

A new option `ignoreWarnings` is added. It would be great if you could verify the fix with the latest [3.3.2-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/mybatis-migrations/3.3.2-SNAPSHOT/) before the final version is out.

Regarding the release date, I think we can release 3.3.2 within a few weeks (but no promises).

Thank you for the valuable feedback!

@h3adache , Thanks for the vote! It helps.

**Comment by jpenalver10** [comment]
Hi @harawata ,

 I verify the fix with 3.3.2-SNAPSHOT, its correct, it works perfectly.

We are waiting the new release.

 Thanks!

**Comment by harawata** [comment]
@jpenalver10 ,
Thank you for testing!
As we discussed on #91 , the default value of `ignore_warnings` is now `true`.
