### ISSUE TITLE
mybatis up doesn't work out-of-the-box

### ISSUE THREAD

**Issue by chb0github** [mybatis/migrations#86]
Using mysql:5.6 on docker
`docker run -d --name mybatis -p 3306:3306  -e MYSQL_ROOT_PASSWORD=my-secret-pw  mysql:5.6 `

I follow the directions 
`migrate --idpattern=00000 init`

Which produces:
`./drivers`
`./environments`
`./scripts`
`./scripts/bootstrap.sql` 
`./scripts/00001_create_changelog.sql`

So far, so good. 

next:
* put mysql driver in the drivers directory: 

 `mysql-connector-java-5.1.40-bin.jar`
`md5sum drivers/mysql-connector-java-5.1.40-bin.jar 
MD5 (drivers/mysql-connector-java-5.1.40-bin.jar) = 2ad5cfbcb388bee5a64c879c208c7652`

and now run:
`migrate up`

Produces:

```sql
$ migrate up
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
------------------------------------------------------------------------
-- MyBatis Migrations - up
------------------------------------------------------------------------
========== Applying: 00001_create_changelog.sql ================================


CREATE TABLE CHANGELOG (
ID NUMERIC(20,0) NOT NULL,
APPLIED_AT VARCHAR(25) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL
);

ALTER TABLE CHANGELOG
ADD CONSTRAINT PK_CHANGELOG
PRIMARY KEY (id);


Error executing: 

CREATE TABLE CHANGELOG (
ID NUMERIC(20,0) NOT NULL,
APPLIED_AT VARCHAR(25) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL
);

ALTER TABLE CHANGELOG
ADD CONSTRAINT PK_CHANGELOG
PRIMARY KEY (id);

.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE CHANGELOG
ADD CONSTRAINT PK_CHANGELOG
PRIMARY KEY (id)' at line 7
------------------------------------------------------------------------
-- MyBatis Migrations FAILURE
-- Total time: 0s
-- Finished at: Wed Oct 11 11:26:11 PDT 2017
-- Final Memory: 15M/479M
------------------------------------------------------------------------

ERROR: Error executing command.  Cause: org.apache.ibatis.jdbc.RuntimeSqlException: Error executing: 

CREATE TABLE CHANGELOG (
ID NUMERIC(20,0) NOT NULL,
APPLIED_AT VARCHAR(25) NOT NULL,
DESCRIPTION VARCHAR(255) NOT NULL
);

ALTER TABLE CHANGELOG
ADD CONSTRAINT PK_CHANGELOG
PRIMARY KEY (id);

.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ALTER TABLE CHANGELOG
ADD CONSTRAINT PK_CHANGELOG
PRIMARY KEY (id)' at line 7

```

**Comment by harawata** [comment]
Yes. For MySQL, `send_full_script` must be set to `true`.
As this is [has been reported several times](https://github.com/mybatis/migrations/search?utf8=%E2%9C%93&q=mysql+send_full_script&type=Issues), I'll add a note on the documentation.

**Comment by chb0github** [comment]
`send_full_script=false` is the answer. This really should be the default so the out-of-the-box init works

**Comment by chb0github** [comment]
I discovered this on my own - it really should be the default setup so the "hello world" example just works

**Comment by harawata** [comment]
Unfortunately, it is database dependent.
The default value was [changed](https://github.com/mybatis/migrations/commit/dade787ee6294f9af959f73376caa5d1f0f9a02b) from `false` to `true` because `false` caused problems with many occasions.
MySQL might be the only database that requires this option to be `false`.

**Comment by chb0github** [comment]
I see. That is a problem. If you can detect the problem and output it in code??

Oh, better: When you generate the changelog file you can put it in the comments section.

Yeah.. I guess documentation is really the only way around this
