### ISSUE TITLE
Stored procs

### ISSUE THREAD

**Issue by chb0github** [mybatis/migrations#88]
I am trying to evaluate MyBatis for migrations and it (along with all other Java based tools) fail on the below syntax because of the delimiter swap.

MyBatis at least has a call-out for this in the properties:

    # A NOTE ON STORED PROCEDURES AND DELIMITERS
    #
    # Stored procedures and functions commonly have nested delimiters
    # that conflict with the schema migration parsing.  If you tend
    # to use procs, functions, triggers or anything that could create
    # this situation, then you may want to experiment with
    # send_full_script=true (preferred), or if you can't use
    # send_full_script, then you may have to resort to a full
    # line delimiter such as "GO" or "/" or "!RUN!".
    #
    # Also play with the autocommit settings, as some drivers
    # or databases don't support creating procs, functions or
    # even tables in a transaction, and others require it.   
    send_full_script=false
 
So, I don't quite get it. What modifications to which files can I make to get this to go? One procedure per file and send whole file? Change the delimiters in the file? Does anyone have any experience on this? I have tried the mysql driver and the mariadb driver. Both choke.

```sql
    DELIMITER ||
    
    CREATE FUNCTION format_time( picoseconds BIGINT UNSIGNED )
    RETURNS varchar(16) CHARSET utf8
       DETERMINISTIC
    BEGIN
    
      IF picoseconds IS NULL THEN
    
        RETURN NULL;
    
      ELSE 
    
        RETURN CAST(CONCAT(ROUND(picoseconds / 1000000000000, 2)) AS DECIMAL(10,6));
    
      END IF;
    
    END;
    ||
    
    DELIMITER ;
```

**Comment by h3adache** [comment]
When you say both choke what do you mean?
When I create stored procs using migrations I usually set the send_full_script to true and delimiter in the `./environments/development.properties` (or whatever environment properties file you are using) [See here](http://www.mybatis.org/migrations/init.html)

```
# This controls how statements are delimited.
# By default statements are delimited by an
# end of line semicolon.  Some databases may
# (e.g. MS SQL Server) may require a full line
# delimiter such as GO.
delimiter=;
```
If that isn't working, send the error message and, if possible, a quick sample

**Comment by chb0github** [comment]
I will definitely send you a fully reproducible case tomorrow.

**Comment by chb0github** [comment]
[Here](https://github.com/chb0github/mybatis-example/) is an example

**Comment by harawata** [comment]
To change the delimiter in migration scripts, you need to use special syntax: `-- @DELIMITER`.
I have sent a PR .
Only a single character is accepted with this syntax, IIRC.

If you are wondering about the syntax, see https://github.com/mybatis/mybatis-3/issues/355 and https://github.com/mybatis/mybatis-3/pull/241 .

**Comment by chb0github** [comment]
Hmm, ok. I will give it a try right now. It does, however, essentially make it so the script can ONLY run with mybatis as this is no longer compatible with the native client. I will Make the changes and run it by our DBAs to see how they feel. 

Alternatively: If a stored procedure was in a single file (or any of these crazy things with switching delimiters) could that also solve the issue? So, let me outline the approach:

1. Convert all Delimter-switching migrations to 1-per file
2. Each file has no delimiter switching. Meaning a `DELIMETER ||` wouldn't even exist in the file
3. Create an environment file that sets `send_full_script=true` (but this may not work with mysql)

Alternative

2. Each file has `DELIMITER ||` at the start and end of the file
3. Create an environment file that sets `send_full_script=false` and `delimiter=||` is set

I am trying really hard to make sure the scripts we have are mysql compatible. But then again, maybe I should. If we intend to take advantage of the `--@undo` feature then you will always have scripts that, if taken as a whole, will do and then undo a feature in one script. Just entertaining feasibility

**Comment by chb0github** [comment]
Ok, so this is interesting and brings up the question: Why swap `DELIMITER ||` for `-- @DELIMITER %` The `DELIMITER` statement was always meant for the client so why not just accept that token instead of creating a new one all-your-own?

I understand it's DB dependent but it seems you could easily discover it through a series of strategies. The first one to succeed determines the dialect. Hibernate uses dialects for a reason
`Set<Strategy> DB_CHECKS = new HashSet<>(Arrays.asList(new OracleStrategy(), new MySqlStrategy()));`

Alternatively, you can use the driver as a fair proxy.

**Comment by harawata** [comment]
> The DELIMITER statement was always meant for the client so why not just accept that token instead of creating a new one all-your-own?

According to https://github.com/mybatis/mybatis-3/issues/355 , to make it valid as SQL.
It is the same reason we write `-- //@UNDO` instead of `UNDO`, I guess.

As `DELIMITER` is a client command and not sent to the server, DB dependency seems irrelevant here.

**Comment by chb0github** [comment]
I am looking at the code now that handles this. 

Because your hide the delimiter switch in comments that means it's completely safe and thus DB agnostic. What I am suggesting is that you make DB-specific determination of the delimiter switch and use the declaration in the file.

[here is the code](https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/jdbc/ScriptRunner.java#L199) That does this.

I propose 2 changes - one really easy and one much more work

1. change this to `cleanedString.split(" ")[1];// get the whole next token` to allow for multi-character delimiters. This is way more common in my experience and Would mean I could make a SQL file native client happy and mybatis happy.
2. `this.delimiter = DELIMTERS.getOrDefault(command,this.delimiter); 

To do number 2 is to basically interpret the `DELIMITER ||` command the same way the client does. 

You could set it up as a simple mapping of known delimiter statements If your command looks up in the delimiter map then it doesn't matter what platform it's on you change it

**Comment by h3adache** [comment]
Hi @chb0github I like your first idea.
I'm not entirely clear why the old code was just taking 1 character.
I commonly use multiple characters in delimiters as well.
I'm not sure what you mean by your 2nd.

**Comment by chb0github** [comment]
I made the change suggested in 1 and already submitted a [PR](https://github.com/mybatis/mybatis-3/pull/1116/files). 

One thing I am really trying hard to do is to have SQL files that are compatible with the native mysql client and with mybatis. I currently can't do that. 

After apply the changes in 1 I re-jiggered one of my problem files to try to be compatible with both. That required a redundant `DELIMITER` declaration: 1 for migrations and 1 for mysql. Observe below:

```sql
DELIMITER $$
-- @DELIMITER $$
Create procedure talentwise_deltaidentifier()
Begin
  Declare rds_type,rcnt,maxreqid INT;
  Declare active_session varchar(10);
  Declare last_run datetime;


  select @@innodb_read_only into rds_type;

  select active,refresh_start into active_session,last_run
  from  s1reporting.refresh_ctl where ctrl_type='delta_identfier';

  -- Continue only if Writer
  if (rds_type=0 and active_session='N') then

    -- Lets update session to be active
    Update s1reporting.refresh_ctl set refresh_start=CURRENT_TIMESTAMP,active='Y' where type='delta_identfier';


    -- Lets Identify Changes

    Insert into s1reporting.refresh_delta (Table_name,change_id,change_date)
    select 'requestque',rq.ReqID,last_run
    from OnPrem.RequestQueue rq
    left join Intelius.ReportGroup rg on rg.detailreportid=rq.DetailedReportID
    where lastmodified >= DATE_ADD( last_run , INTERVAL  -1 HOUR_MINUTE ) ;

    Update s1reporting.refresh_ctl set active='N' where ctrl_type='delta_identfier';

  end if;

end
$$
```

The mysql client processes this file just fine. Migrations does not. With the code in place it errors and upon debug, this is the actual string it's sending to the server:


```

DELIMITER $$
Create procedure talentwise_deltaidentifier()
  Begin
    Declare rds_type,rcnt,maxreqid INT;
    Declare active_session varchar(10);
    Declare last_run datetime;
    select @@innodb_read_only into rds_type;
    select active,refresh_start into active_session,last_run
    from  s1reporting.refresh_ctl where ctrl_type='delta_identfier';
    if (rds_type=0 and active_session='N') then
      Update s1reporting.refresh_ctl set refresh_start=CURRENT_TIMESTAMP,active='Y' where type='delta_identfier';
      Insert into s1reporting.refresh_delta (Table_name,change_id,change_date)
        select 'requestque',rq.ReqID,last_run
        from OnPrem.RequestQueue rq
          left join Intelius.ReportGroup rg on rg.detailreportid=rq.DetailedReportID
        where lastmodified >= DATE_ADD( last_run , INTERVAL  -1 HOUR_MINUTE ) ;
      Update s1reporting.refresh_ctl set active='N' where ctrl_type='delta_identfier';
    end if;
  end


```

the `DELIMTER $$` is meant for the client to process to parse not the server. But even if the server did parse it it would need a terminating delimiter which isn't in this line.

As for number 2, let me try even harder to explain this:

Do not use your own delimiter declaration anymore: use the native one present in the sql script.

So
1. Get rid of `--@DELIMITER %` 
2. Use `DELIMITER %`

Now, this is where you say: _WAIT! But then it's specific to the DB dialect!_ Yes, it is. And it is by intent. But, this isn't as hard to manage as it might seem and has the advantage of having SQL that's compatible with the native client and migrations.

A straightforward way to handle this kind of thing would be to have a lookup table of commands with the default being to send the line to the server. Something like this:


```java
Map<String,Consumer<String>> COMMANDS = new HashMap<>();
COMMANDS.put("DELIMITER", c -> this.delimiter = c); // mysql version
COMMANDS.put("CHANGE", c -> this.delimiter = c.split(" ")[1]); // ORACLE version CHANGE / %

Consumer<String> whatToDo = COMMANDS.getOrDefault(command,c -> sendToDb(c));
whatToDo.accept(command);
```
The above approach is simple and should work

A truly robust approach to this all would be to first-and-formost determine what DB your dealing with and utterly pivot strategies for working with the DB following the [Abstract Factory Patter](https://en.wikipedia.org/wiki/Abstract_factory_pattern)

**Comment by harawata** [comment]
> get the whole next token to allow for multi-character delimiters.

+1 to this as well.

Regarding the second one, though, I honestly don't see any reason why migration scripts that are for MyBatis Migrations need to be compatible with MySQL client (or any other client for that matter).
If you really want this, how about rewriting the script in pre-hook (and reverting it in post-hook if necessary)?

**Comment by chb0github** [comment]
It's a 2 fold case:

1. If you can have your cake and eat it too, why not?
2. the use of a delimiter declaration of `--@DELIMITER` is redundant. This brings up the mantra of [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)
3. Reduces friction to acceptance by weary DBAs - if all hell breaks loose with mybatis they can still do the job the old fashioned way.

Pre/post hook requires me maintaining state between before/after. Like, in the `after_each_hook` I would need to know that the `before_each_hook` had actually modified the delimiter and that I need to set it back. I guess I can do something hacky like put the previous delimiter into `System.properties`

I won't go back-and-forth all day on the matter because it just isn't that important to me and it's easy to go between them. We will live without it. My second approach could be some work. If it really, really, really becomes an issue on our end I will either take your script approach and try to apply it or reopen this issue.

**Comment by harawata** [comment]
I found one good use case that justifies the change. :D
When executing `migrate script`, the generated script may be run on another client and there is a clear advantage in using native delimiter syntax.

To keep the implementation DB agnostic, I'll probably add a new option `delimiter_prefix` or `delimiter_pattern`.
Give me some time, please.

**Comment by chb0github** [comment]
That won't be DB agnostic. I suppose this discussion can continue in another issue as the one dealing with stored proc is concluded.
