### ISSUE TITLE
Migrate support for OS MINGW64

### ISSUE THREAD

**Issue by jpenalver10** [mybatis/migrations#94]
Hello guys!

I'm currently using MinGW (http://www.mingw.org/) as my default shell environment over windows 10. It's currently distributed with GIT client for windows and very useful for windows users.

When I try to run migrate in this bash, I receive this error:

```
jpenalver@JOAQUINPENALVER MINGW64 /c/git/wtn-geo-searcher/migrations (develop) $ migrate info
Error: could not find or load main class org.apache.ibatis.migration.Migrator
```

I historically solve this problem editing the migrate script *nix, adding the next line in the resolution of OS specific support to support MINGW64:

```
case " `uname`" in
  CYGWIN*) cygwin=true ;;
  MINGW64*) cygwin=true ;;
  Darwin*) darwin=true
```

The system identification in mingw is:

```
$ uname -a
MINGW64_NT-10.0 JOAQUINPENALVER 2.9.0(0.318/5/3) 2017-10-05 15:05 x86_64 Msys
```

I dont know if this is the best solution and if is reasonable to add this support.

Thanks!

**Comment by harawata** [comment]
This may be a duplicate of #58 .
The script is generated by [Appassembler maven plugin](https://github.com/mojohaus/appassembler/).
I already [reported](https://github.com/mojohaus/appassembler/issues/55) the issue on their tracker, but as you have a workaround, I would suggest you to send a PR and see if it's accepted.

**Comment by jpenalver10** [comment]
ooops sorry! Ok, maybe I send PR to Appassembler.

thanks!

**Comment by jpenalver10** [comment]
I close this issue for duplication.

Thanks.
